# Generated by Django 3.1.7 on 2021-06-25 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0021_patientprescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='mobile',
            field=models.PositiveIntegerField(max_length=20, null=True),
        ),
    ]
