# Generated by Django 3.1.7 on 2021-06-25 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0022_auto_20210625_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='mobile',
            field=models.PositiveIntegerField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mobile',
            field=models.PositiveIntegerField(max_length=11),
        ),
    ]
