# Generated by Django 3.1.7 on 2021-06-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0023_auto_20210625_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='mobile',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
